import Head from 'next/head'
import Slider from '../components/Slider'
import Packages from '../components/Packages'
import Featured from '../components/featured'
import { Box } from '@mui/material'

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Tourist App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Slider />
        <Packages/>
        <Featured items={data}/>
      </Box>
    </>
  )
}


const URL = process.env.NODE_ENV === 'production' ? 'https://touristapp.vercel.app' : 'http://localhost:3000';

export async function getServerSideProps() {
  const response = await fetch(`${URL}/api/house`,{method:'GET'});
  const result = await response.json();
  return {
    props: {
      data:result.data
    }, 
  }
}
