import Head from 'next/head'
import Slider from '../components/Slider'
import Packages from '../components/Packages'
import Featured from '../components/featured'
import { Box } from '@mui/material'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ margin:{xs: '120px 10px 20px 10px',sm: '120px 50px 20px 50px', md: '120px 50px 50px 50px'}}}>
        {/* <Slider /> */}
        <Packages/>
        <Featured />
      </Box>


    </>
  )
}
