import Head from 'next/head'
import Slider from '../components/Slider'
import Packages from '../components/Packages'
import Featured from '../components/featured'
import { Box } from '@mui/material'


export default function Home() {
  return (
    <>
      <Head>
        <title>Tourist App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Slider />
        <Packages/>
        <Featured />
      </Box>


    </>
  )
}
// export async function getServerSideProps() {
//   const response = await fetch('http://localhost:3000/api/house',{method:'GET'});
//   const result = await response.json();
//   return {
//     props: {
//       cards:result.data
//     }, 
//   }
// }
